### PR TITLE
Handle waiting and deleted connections

### LINKED ISSUE #364: Change the "waiting" label on a connection after 30 seconds to "problem; connect again" (40-80 subs)
Users are sitting around waiting for hours on a connection, wondering what they need to do next. If a connection fails, it's very easy just to try again.

### PR DESCRIPTION
**Pull request by TripleSpeeder**
Changes:
- Don't show flag button for connections in waiting state
- Track 'Add Connection' operation also on the responder side (the person that scanned other persons code). This makes the connection change automatically from 'waiting' to 'connected'. 
- If a connection is in waiting state for more than 1 minute mark it as stale:
  - update the connection label to "Connection failed. Please try again".
  - add an 'X' button to the connection that enables to remove the stale connection (after confirmation)
- If a connection is in "deleted" state (you have been flagged by the other person), also show the 'X' button instead of the flag button, so you can remove the deleted connection

This should fix #364 and partly deals with #311.

### CODE REVIEW

File: BrightID/src/components/NewConnectionsScreens/actions/profile.js [hunk 1]
```diff
@@ -81,7 +81,6 @@ export const fetchProfile = (qrCodeData) => async (
 
     if (profileData && profileData.data) {
       try {
-        console.log(`fetched profile: ${profileData.data}`);
```
Comment (adamstallard) [inline BrightID/src/components/NewConnectionsScreens/actions/profile.js:84]: Curious why this was removed

**Comment by TripleSpeeder** [comment]
> I think your coding style inside of components would benefit from using hooks. I just started using them, and I think the code I'm writing is simpler, and the components are slightly more performant. If you want to switch any component to a functional style, I would be okay with it.

I'm also big fan of functional components and hooks :-) But I would prefer to do such a refactoring in a dedicated PR without functional changes, to keep things separated and easier to review.

File: BrightID/src/App.js [hunk 2]
```diff
@@ -35,7 +35,6 @@ export const App = () => {
   useEffect(() => {
     const timerId = setInterval(() => {
       pollOperations();
-      console.log('polling operations');
```
Comment (RnbWd) [inline BrightID/src/App.js:38]: thank you
